#!/usr/bin/env python3
"""
inject_media.py - Injects native PDF Movie and Screen annotations into PDFs generated by Ipe.

Usage:
    python3 inject_media.py input.pdf [output.pdf]

This script finds link annotations generated by Ipe with URLs of format:
    movie:<filepath>?controls=1&loop=1&autostart=1
and converts them into native PDF /Subtype /Movie annotations supported by
Pympress, pdfpc, and other presentation tools.
"""

import sys
import os
import pathlib
import urllib.parse
import pikepdf


def inject_media_annotations(input_pdf_path: str, output_pdf_path: str = None) -> int:
    if output_pdf_path is None:
        output_pdf_path = input_pdf_path

    input_path = pathlib.Path(input_pdf_path).resolve()
    if not input_path.exists():
        print(f"Error: File not found: {input_pdf_path}", file=sys.stderr)
        return -1

    pdf = pikepdf.Pdf.open(input_path, allow_overwriting_input=True)
    count = 0

    for page_idx, page in enumerate(pdf.pages):
        if "/Annots" not in page:
            continue

        new_annots = []
        for annot in page.Annots:
            converted = False
            subtype = str(annot.get("/Subtype", ""))

            # Check if this annotation is a Link with a movie: / media: URL
            if subtype == "/Link" and "/A" in annot:
                action = annot["/A"]
                uri_str = None
                if "/URI" in action:
                    uri_str = str(action["/URI"])
                elif "/F" in action:
                    uri_str = str(action["/F"])

                if uri_str and (uri_str.startswith("movie:") or uri_str.startswith("media:")):
                    raw = uri_str.split(":", 1)[1]
                    parts = raw.split("?", 1)
                    filepath = parts[0]
                    params = {}
                    if len(parts) > 1:
                        for item in parts[1].split("&"):
                            if "=" in item:
                                k, v = item.split("=", 1)
                                params[k] = v

                    show_controls = params.get("controls", "1") != "0"
                    repeat = params.get("loop", "1") != "0"
                    autostart = params.get("autostart", "1") != "0"

                    # Normalize filepath relative to the PDF directory if needed
                    # If absolute path, keep it, or make it relative if in the same tree
                    target_file = filepath

                    # Create native PDF /Subtype /Movie annotation
                    movie_annot = pikepdf.Dictionary({
                        "/Type": pikepdf.Name("/Annot"),
                        "/Subtype": pikepdf.Name("/Movie"),
                        "/Rect": annot.Rect,
                        "/Movie": pikepdf.Dictionary({
                            "/F": pikepdf.String(target_file),
                        }),
                        "/A": pikepdf.Dictionary({
                            "/Mode": pikepdf.Name("/Repeat" if repeat else "/Once"),
                            "/ShowControls": show_controls,
                        }),
                        "/Border": pikepdf.Array([0, 0, 0]),
                    })

                    new_annots.append(movie_annot)
                    count += 1
                    converted = True

            if not converted:
                new_annots.append(annot)

        page.Annots = pikepdf.Array(new_annots)

    pdf.save(output_pdf_path)
    print(f"Injected {count} media annotation(s) into: {output_pdf_path}")
    return count


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 inject_media.py input.pdf [output.pdf]")
        sys.exit(1)

    input_pdf = sys.argv[1]
    output_pdf = sys.argv[2] if len(sys.argv) > 2 else input_pdf
    cnt = inject_media_annotations(input_pdf, output_pdf)
    if cnt < 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
