#!/usr/bin/env python3
"""
inject_media.py - Injects native PDF Movie and Screen annotations into PDFs generated by Ipe.

Usage:
    python3 inject_media.py input.pdf [output.pdf]

This script finds link annotations generated by Ipe with URLs of format:
    movie:<filepath>?controls=1&loop=1&autostart=1
and converts them into native PDF /Subtype /Movie annotations supported by
Pympress, pdfpc, and other presentation tools.
"""

import sys
import os
import pathlib
import urllib.parse
import pikepdf


def inject_media_annotations(input_pdf_path: str, output_pdf_path: str = None) -> int:
    if output_pdf_path is None:
        output_pdf_path = input_pdf_path

    input_path = pathlib.Path(input_pdf_path).resolve()
    if not input_path.exists():
        print(f"Error: File not found: {input_pdf_path}", file=sys.stderr)
        return -1

    pdf = pikepdf.Pdf.open(input_path, allow_overwriting_input=True)
    count = 0

    for page_idx, page in enumerate(pdf.pages):
        if "/Annots" not in page:
            continue

        new_annots = []
        for annot in page.Annots:
            converted = False
            subtype = str(annot.get("/Subtype", ""))

            # Check if this annotation is a Link with a movie: / media: URL
            if subtype == "/Link" and "/A" in annot:
                action = annot["/A"]
                uri_str = None
                if "/URI" in action:
                    uri_str = str(action["/URI"])
                elif "/F" in action:
                    uri_str = str(action["/F"])

                if uri_str and (uri_str.startswith("movie:") or uri_str.startswith("media:")):
                    raw = uri_str.split(":", 1)[1]
                    parts = raw.split("?", 1)
                    filepath = parts[0]
                    params = {}
                    if len(parts) > 1:
                        for item in parts[1].split("&"):
                            if "=" in item:
                                k, v = item.split("=", 1)
                                params[k] = v

                    show_controls = params.get("controls", "1") != "0"
                    repeat = params.get("loop", "1") != "0"
                    autostart = params.get("autostart", "1") != "0"

                    # Normalize filepath relative to the PDF directory if needed
                    target_file = filepath
                    # On Linux/Wayland, if a .webm (VP8/VP9) counterpart exists, prefer it for native GStreamer embedding
                    candidate_path = input_path.parent / target_file
                    if target_file.lower().endswith((".mp4", ".mov", ".mkv")):
                        stem_webm = candidate_path.with_suffix(".webm")
                        if stem_webm.exists():
                            target_file = str(stem_webm.name)
                        elif pathlib.Path(target_file).with_suffix(".webm").exists():
                            target_file = str(pathlib.Path(target_file).with_suffix(".webm"))

                    # MIME type determination
                    ext = pathlib.Path(target_file).suffix.lower()
                    mime_map = {
                        ".webm": "video/webm",
                        ".mp4": "video/mp4",
                        ".m4v": "video/mp4",
                        ".mov": "video/quicktime",
                        ".ogg": "video/ogg",
                        ".ogv": "video/ogg",
                        ".avi": "video/x-msvideo",
                        ".mkv": "video/x-matroska",
                    }
                    mime_type = mime_map.get(ext, "video/webm")

                    # Create native PDF 1.7 Screen Annotation + Rendition Action
                    # This enables Poppler / Pympress to read `autoplay=True` and start playback upon page entry!
                    filespec = pdf.make_indirect(pikepdf.Dictionary({
                        "/Type": pikepdf.Name("/Filespec"),
                        "/F": pikepdf.String(target_file),
                        "/UF": pikepdf.String(target_file),
                    }))

                    media_clip = pdf.make_indirect(pikepdf.Dictionary({
                        "/Type": pikepdf.Name("/MediaClip"),
                        "/S": pikepdf.Name("/MCD"),
                        "/N": pikepdf.String(f"Clip: {target_file}"),
                        "/D": filespec,
                        "/CT": pikepdf.String(mime_type),
                    }))

                    play_params = pdf.make_indirect(pikepdf.Dictionary({
                        "/Type": pikepdf.Name("/MediaPlayParams"),
                        "/A": pikepdf.Dictionary({
                            "/Type": pikepdf.Name("/MediaAutoplay"),
                            "/A": autostart,
                        }),
                        "/C": pikepdf.Dictionary({
                            "/Type": pikepdf.Name("/MediaControls"),
                            "/C": show_controls,
                        }),
                        "/RC": 0 if repeat else 1,
                    }))

                    rendition = pdf.make_indirect(pikepdf.Dictionary({
                        "/Type": pikepdf.Name("/Rendition"),
                        "/S": pikepdf.Name("/MR"),
                        "/N": pikepdf.String(f"Rendition: {target_file}"),
                        "/C": media_clip,
                        "/P": play_params,
                    }))

                    screen_annot = pdf.make_indirect(pikepdf.Dictionary({
                        "/Type": pikepdf.Name("/Annot"),
                        "/Subtype": pikepdf.Name("/Screen"),
                        "/Rect": annot.Rect,
                        "/P": page.obj,
                        "/Border": pikepdf.Array([0, 0, 0]),
                    }))

                    action = pdf.make_indirect(pikepdf.Dictionary({
                        "/Type": pikepdf.Name("/Action"),
                        "/S": pikepdf.Name("/Rendition"),
                        "/OP": 0,
                        "/R": rendition,
                        "/AN": screen_annot,
                    }))

                    screen_annot["/A"] = action
                    new_annots.append(screen_annot)
                    count += 1
                    converted = True


            if not converted:
                new_annots.append(annot)

        page.Annots = pikepdf.Array(new_annots)

    pdf.save(output_pdf_path)
    print(f"Injected {count} media annotation(s) into: {output_pdf_path}")
    return count


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 inject_media.py input.pdf [output.pdf]")
        sys.exit(1)

    input_pdf = sys.argv[1]
    output_pdf = sys.argv[2] if len(sys.argv) > 2 else input_pdf
    cnt = inject_media_annotations(input_pdf, output_pdf)
    if cnt < 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
